### DISCUSSION TITLE
Make it easy to define metrics for different values of a categorical dimension

### DISCUSSION THREAD

**Discussion by siljamardla** [dbt-labs/metricflow#1536] [Ideas]
A very typical use case for metrics is to define a set of metrics that use the same measure and a filter on the same field, but the filter value would be different. For example:
```yml
metrics:
  - name: rides_orders_in_finished_state
    label: Rides Orders in Finished State
    description: {{ doc('rides_orders_in_finished_state') }}
    type: simple
    type_params:
      measure: rides_orders_utc
    filter: {{ Dimension('rides_order__order_state') }} = 'finished'
  - name: rides_orders_in_cancelled_state
    label: Rides Orders in Cancelled State
    description: {{ doc('rides_orders_in_cancelled_state') }}
    type: simple
    type_params:
      measure: rides_orders_utc
    filter: {{ Dimension('rides_order__order_state') }} = 'cancelled'
```
As you see, at the moment we need to define each metric individually. 
Could we simplify this process somehow to allow the metric definitions to be more dynamic?
```yml
metrics:
  - name: rides_orders_in_{{rides_order__order_state}}_state
    label: Rides Orders in {{rides_order__order_state}} State
    description: {{ doc('rides_orders_in_{{rides_order__order_state}}_state') }}
    type: simple
    type_params:
      measure: rides_orders_utc
    filter: {{ Dimension('rides_order__order_state') }} = <input_at_metric_query_time>
```
and 
```
mf query --metrics rides_orders_in_<finished>_state
```
where <finished> is something that we insert at query time.
