### DISCUSSION TITLE
Allow defining versions of metrics / Introduce the concept of "base metric"

### DISCUSSION THREAD

**Discussion by siljamardla** [dbt-labs/metricflow#1537] [Ideas]
There is often a case when we have multiple versions of the same metric, for example:
- revenue_in_eur_wo_vat
- revenue_in_local_currency_wo_vat
- revenue_in_eur_with_vat
- revenue_in_local_currency_with_vat
or
- ride_distance_in_m
- rides_distance_in_km

These are slightly different use cases: for the revenue metric we actually have 4 different underlying columns in the fact table while for the distance metrics we would define the first as a simple metric and the second would be a derived metric on top of the simple metric. 

The common annoyance here is that we have to maintain each of these metrics separately, make sure we have some naming convention in place and produce very similar YML. I have even written an [article](https://www.linkedin.com/pulse/managing-all-variations-dbt-metrics-silja-m%25C3%25A4rdla-grcnf/?trackingId=IIYm2KvUREOzdfFPOeF6Pg%3D%3D) on how I manage these.

I would like there to be some concept of "base metric" that would hold all the common aspects: name, documentation, label etc. 
And then we could have additional configurations to define the differences. Maybe something like:
```yml
metrics:
  - name: rides_total_revenue
    label: Rides Total Revenue
    description: {{ doc('rides_total_revenue') }}
    type: simple
    version: 
      - eur_with_vat:
          label_addition: in Euros, with VAT
          type_params:
            measure:
              name: sum_eur_with_vat
          additional_description: {{ doc('generic_eur_with_vat') }}
      - eur_wo_vat:
          label_addition: in Euros, without VAT
          type_params:
            measure:
              name: sum_eur_wo_vat
          additional_description: {{ doc('generic_eur_wo_vat') }}
```
This would automatically create metric versions that I could query:
```
mf query --metrics rides_total_revenue_eur_with_vat,rides_total_revenue_eur_wo_vat
```
The labels and documentation would be appended where added etc.

For the second use case with units it might be something like:
```yml
metrics:
  - name: rides_distance
    label: Rides Distance
    description: {{ doc('rides_distance') }}
    type: simple
    unit: 
      - m:
          is_default: true
          label_addition: in metres
          type_params:
            measure:
              name: distance_m
          additional_description: {{ doc('generic_unit_metres') }}
      - km:
          label_addition: in kilometres
          conversion_type: divide
          conversion_number: 1000
          additional_description: {{ doc('generic_unit_km') }}
```

These suggestions are not seriously thought through, I'm just trying to put some idea out there. 

Might also relate to https://github.com/dbt-labs/metricflow/discussions/1536
