### ISSUE TITLE
[Feature] Allow referencing entities using dunders(__) instead of entity_path in filters. 

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#1003]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Say I have the following semantic model and metrics: 
```
semantic_models:
 - name: properties_d
   entities:
    - name: triebeca_id
      type: primary
    - name: address
      type: foreign
   measure: 
    - name: propetry_count
      agg: sum
metrics:
  - name: managed_homes_count
    description: No of Managed Homes
    type: simple
    label: Managed Homes Count
    type_params:
      measure: property_count
    filter: |
      ({{Entity('address'}} is not null
```

If I try to reference `{{Entity('address')}}` in the filter I get an error. I need to add the entity path to get this to work i.e `({{Entity('address',['tribeca_id'])}}`. If I try to use dunders I also get an `error : ParseWhereFilterException("Entity name is in an incorrect format: 'tribeca_id__address'. It should not contain any dunders (double underscores, or __)."))]. `

It looks like we're requiring entities be referenced in the format primary_entity__foreign_entity. We should enable reference to entities using dunders i.e `{{Entity('tribeca_id__address')}}` as a shorthand for this instead of requiring the entity path. 

### Describe alternatives you've considered

I can use the entity path syntax, but this is inconsistent with how we reference dimensions. 

### Who will this benefit?

This helps developers be more efficient and consistent when writing metric definitions.
