### ISSUE TITLE
[SL-1704] [SL-1703] [Feature] Enable `fill_nulls_with` and `join_to_timespine` on metric spec

### ISSUE THREAD

**Issue by courtneyholcomb** [dbt-labs/metricflow#1031]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

Currently, `fill_nulls_with` and `join_to_timespine` are only available on metric input measures. This can result in unwanted nulls if the measure is nested in a ratio or derived metric and then joined to other metrics. If we add those options to the metric config, users will be able to resolve that issue and also have more granular control over when nulls are filled.

This means that after the metric is calculated, the metric subquery can be joined to a time spine subquery to fill missing dates, and then coalesce nulls to the integer value specified in the `fill_nulls_with` property. We also may consider allowing variables and other expressions to be used to fill nulls instead of only integers.

<sub>[SL-1703](https://linear.app/dbt-labs/issue/SL-1703/[feature]-enable-fill-nulls-with-and-join-to-timespine-on-metric-spec)</sub>

**Comment by siljamardla** [comment]
Adding some business context, to push the priority up.

Imagine this very common scenario:
total_revenue = 
    revenue_from_business_line1 (a business line with regular incremental revenue) 
    + revenue_from_business_line2 (a business line with rare but big revenue, so has nulls in some periods!) 
    + revenue_from_business_line3 (very seasonal business, so has nulls in some periods!)
total_cost = cost_from_business_line1 + cost_from_business_line2 + headquarter_costs
total_net (income/cost) = total revenue - total cost
cost_to_revenue_rate = total_cost/total_revenue

Now, we want time based reporting (daily, weekly, monthly metric values). As soon as ANY of the input metrics have a NULL in them for this particular period, the whole thing will be NULL. Total revenue is NULL because we didn't have any revenue to show from business line 3 !?! 

No workaround for this feature missing, as far as I know. 

This feature should have the highest priority!

**Comment by Jstein77** [comment]
@siljamardla I think there is an easy workaround for this. You can add coalesce statements to the `expr:` for derived metrics. Going back to your example in #1098. I created another metric which is the sum of metric8 and metric7 and added a coalesce statement in the expression 
```
  - name: metric10
    label: metric10
    type: derived
    type_params:
      metrics:
        - name: metric7
        - name: metric8
      expr: coalesce(metric7,0) + coalesce(metric8,0)
``` 
Metric10 is able to safely sum metric7 and metric8 even when there are nulls present. 
| METRIC_TIME__DAY   | CALENDAR_DATE_LOCAL   |   USER_ID |   METRIC1 |   METRIC7 |   METRIC8 |   METRIC10 |
|:-------------------|:----------------------|----------:|----------:|----------:|----------:|-----------:|
| 2024-01-01         | 2024-01-01            |      1.00 |         1 |      3.00 |    nan    |          3 |
| 2024-01-01         | 2024-01-01            |      2.00 |         1 |      3.00 |      3.00 |          6 |
| 2024-01-01         | 2024-01-01            |      3.00 |         0 |    nan    |      3.00 |          3 |
| 2024-01-02         | 2024-01-02            |      1.00 |         1 |      3.00 |    nan    |          3 |
| 2024-01-03         | 2024-01-03            |      2.00 |         0 |    nan    |      3.00 |          3 |

Definitely agree that it would be better to support plumbing the null values all the way down to the input metric, but with this approach we are still able to accurately calculate the metric value for metric 10 for user id = 1 on 2024-01-01. This makes this feature feel less urgent to me since there is a workaround. 

I believe adding a coalesce to the `expr` should allow you to calculate the total_net metric you described as well.  Let me know if there is a case i'm not thinking about.

**Comment by siljamardla** [comment]
Thanks @Jstein77, you really saved me here!
@courtneyholcomb, please update the [fill_nulls_with docs](https://docs.getdbt.com/docs/build/fill-nulls-advanced) with these examples (metric10 and metric11). 

I'm also extending this to cover the ratio metric case:
```
  - name: metric11
    label: metric11
    type: derived # instead of ratio, because we want to do manual null handling
    type_params:
      metrics:
        - name: metric7
        - name: metric8
      expr: COALESCE(metric7,0) + NULLIF(metric8,0)
```

I also tried adding the coalesce into the `ratio` metric definition, but that throws an error. 
```
  - name: metric12
    label: metric12
    type: ratio
    type_params:
      numerator: COALESCE(metric7,0)
      denominator: metric7
```
That's why I've used `derived` also for `ratio`.

**Comment by siljamardla** [comment]
After some additional testing I have to come back here. The workaround only solves parts of the problem. 

I have made updates to my metric7, metric8 and metric9. I've also added your metric10. 

```YAML
  # Derived metrics

  - name: metric7
    label: metric7
    type: derived
    type_params:
          expr: COALESCE(metric1_for_metric7,0) + COALESCE(metric2_for_metric7,0) + COALESCE(metric3_for_metric7,0)
          metrics:
            - name: metric1
              alias: metric1_for_metric7
            - name: metric2
              alias: metric2_for_metric7
            - name: metric3
              alias: metric3_for_metric7

  - name: metric8
    label: metric8
    type: derived
    type_params:
          expr: COALESCE(metric4_for_metric8,0) + COALESCE(metric5_for_metric8,0) + COALESCE(metric6_for_metric8,0)
          metrics:
            - name: metric4
              alias: metric4_for_metric8
            - name: metric5
              alias: metric5_for_metric8
            - name: metric6
              alias: metric6_for_metric8

  - name: metric9
    label: metric9
    type: derived
    type_params:
          expr: COALESCE(metric7_for_metric9,0) / NULLIF(COALESCE(metric8_for_metric9,0),0)
          metrics:
            - name: metric7
              alias: metric7_for_metric9
            - name: metric8
              alias: metric8_for_metric9

  - name: metric10
    label: metric10
    type: derived
    type_params:
          expr: COALESCE(metric7_for_metric9,0) + COALESCE(metric8_for_metric9,0)
          metrics:
            - name: metric7
              alias: metric7_for_metric9
            - name: metric8
              alias: metric8_for_metric9
```
Querying all of them together:
```
mf query --metrics metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9,metric10\
 --group-by calendar_date_local,user_id\
 --order calendar_date_local,user_id
```
Will return:
| calendar_date_local   |   user_id |   metric1 |   metric2 |   metric3 |   metric4 |   metric5 |   metric6 |   metric7 |   metric8 |   metric9 |   metric10 |
|:----------------------|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|-----------:|
| 2024-01-01            |         1 |         1 |         1 |         1 |         0 |         0 |         0 |      3.00 |    nan    |           |          3 |
| 2024-01-01            |         2 |         1 |         1 |         1 |         1 |         1 |         1 |      3.00 |      3.00 |      1.00 |          6 |
| 2024-01-01            |         3 |         0 |         0 |         0 |         1 |         1 |         1 |    nan    |      3.00 |      0.00 |          3 |
| 2024-01-02            |         1 |         1 |         1 |         1 |         0 |         0 |         0 |      3.00 |    nan    |           |          3 |
| 2024-01-03            |         2 |         0 |         0 |         0 |         1 |         1 |         1 |    nan    |      3.00 |      0.00 |          3 |

**Comment by siljamardla** [comment]
I have added a third table (in this table we have data for user_id 4 and 5, nothing for 1, 2 and 3):
id |	user_id |	calendar_date_local |	value33
-- | -- | -- | -- 
1 |	4 |	2024-01-01 |	1
2 |	5 |	2024-01-03 |	1

I have defined a metric on that third table: 
```
  - name: metric33
    label: metric33
    type: simple
    type_params:
      measure:
        name: sum_of_value33
        fill_nulls_with: 0
        join_to_timespine: true
```
I am now querying all of the above plus the new metric:
```
mf query --metrics metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9,metric10,metric33\
 --group-by calendar_date_local,user_id\
 --order calendar_date_local,user_id
```
and voila, we see the `null` problem also in metric10:
| calendar_date_local   |   user_id |   metric1 |   metric2 |   metric3 |   metric4 |   metric5 |   metric6 |   metric7 |   metric8 |   metric9 |   metric10 |   metric33 |
|:----------------------|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|-----------:|-----------:|
| 2024-01-01            |         1 |         1 |         1 |         1 |         0 |         0 |         0 |      3.00 |    nan    |           |       3.00 |          0 |
| 2024-01-01            |         2 |         1 |         1 |         1 |         1 |         1 |         1 |      3.00 |      3.00 |      1.00 |       6.00 |          0 |
| 2024-01-01            |         3 |         0 |         0 |         0 |         1 |         1 |         1 |    nan    |      3.00 |      0.00 |       3.00 |          0 |
| 2024-01-01            |         4 |         0 |         0 |         0 |         0 |         0 |         0 |    nan    |    nan    |           |     nan    |          1 |
| 2024-01-02            |         1 |         1 |         1 |         1 |         0 |         0 |         0 |      3.00 |    nan    |           |       3.00 |          0 |
| 2024-01-03            |         2 |         0 |         0 |         0 |         1 |         1 |         1 |    nan    |      3.00 |      0.00 |       3.00 |          0 |
| 2024-01-03            |         5 |         0 |         0 |         0 |         0 |         0 |         0 |    nan    |    nan    |           |     nan    |          1 |

## How to fix it? 
It should be relatively simple to add a `fill_nulls_with` config to **derived** metrics and then use it in the outer most SELECT. This config would only handle the **final** output while the null handling within a derived metric calculation would remain a part of the derived metric definition, as introduced in the workaround. In fact, the workaround is starting to look like part of the actual solution. What do you think?
