### ISSUE TITLE
[Bug] Conversion metric with window fails on BigQuery

### ISSUE THREAD

**Issue by KayakinKoder** [dbt-labs/metricflow#1073]
### Is this a new bug in dbt-core?

- [X] I believe this is a new bug in dbt-core
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Conversion metrics without a window seem to work as expected with the bigquery adapter.

Adding a window e.g. `window: 7 days` causes the following error:

```
Encountered an error: error querying against the semantic layer: INVALID_ARGUMENT: [FlightSQL] [Simba][BigQueryJDBCDriver](100032) Error executing query job. Message: 400 Bad Request
POST https://bigquery.googleapis.com/bigquery/v2/projects/myproject/jobs
{
  "code": 400,
  "errors": [
    {
      "domain": "global",
      "location": "q",
      "locationType": "parameter",
      "message": "No matching signature for operator > for argument types: TIMESTAMP, DATETIME. Supported signature: ANY > ANY at [46:11]",
      "reason": "invalidQuery"
    }
  ],
  "message": "No matching signature for operator > for argument types: TIMESTAMP, DATETIME. Supported signature: ANY > ANY at [46:11]",
  "status": "INVALID_ARGUMENT"
} (InvalidArgument; Prepare)
```

### Expected Behavior

No error occurs

### Steps To Reproduce

1. Create a simple conversion metric. Our exact metric:

```
- name: conv_completetrial_to_purchases
  description: "Conversion rate from completing trial to purchasing within 7 days"
  type: conversion
  label: Completed First Trial to Purchase Conversion Rate (7-day window)
  type_params:
    conversion_type_params:
      entity: customer
      base_measure:
        name: customers_firsttrialdt
      conversion_measure:
        name: customers_firstpurchdt
      window: 7 days
```
Note that the `agg_time_dimension` field for both `customers_firsttrialdt` and `customers_firstpurchdt` is of type TIMESTAMP.

2. Query this metric, and you'll reproduce the error
3. Remove the window, and the query will be successful

### Environment

```markdown
dbt Cloud=1.7.8
Registered adapter: bigquery=1.7.6
```

**Comment by KayakinKoder** [comment]
Thank you, so not a bug, it's the expected behavior and can be closed unless I think.

If others make their way here in future you can dig into the discussions above; from what I understand:

- While https://stackoverflow.com/questions/47713945/bigquery-datetime-vs-timestamp/47724366#47724366 may make sense for many use cases, regarding metrics it may make more sense to use timezone agnostic DATETIME
- MetricFlow doesn't currently support time zone aware TIMESTAMP
- So, you could....
  - Convert your TIMESTAMP values to DATETIMEs in your warehouse, if you don't think time zone aware data is necessary for your use cases
  - Or duplicate your TIMESTAMP values as DATETIME in your warehouse
  - Or cast your time dimensions from TIMESTAMP to DATETIME in metricflow, e.g.:
  
  ```
  dimensions:
  - name: created_at
    description: Datetime user created their account
    type: time
    expr: CAST(created_at as DATETIME)
    type_params:
      time_granularity: day
```
