### ISSUE TITLE
[Bug] Derived and ratio metrics do not consider fill_nulls_with

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/metricflow#1098]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have 2 independent tables:

id | user_id | calendar_date_local | value1 | value2 | value3
-- | -- | -- | -- | -- | --
1 | 1 | 2024-01-01 | 1 | 1 | 1
2 | 1 | 2024-01-02 | 1 | 1 | 1
3 | 2 | 2024-01-01 | 1 | 1 | 1

id | user_id | calendar_date_local | value4 | value5 | value6
-- | -- | -- | -- | -- | --
1 | 2 | 2024-01-01 | 1 | 1 | 1
2 | 2 | 2024-01-03 | 1 | 1 | 1
3 | 3 | 2024-01-01 | 1 | 1 | 1

Notice that the first table doesn't have user_id=3 and the second table doesn't have user_id=1.

I have 3 simple metrics based on table1: metric1, metric2, metric3 (defined as sum of the corresponding value column)
I have 3 simple metrics based on table2: metric4, metric5, metric6
Both tables have user_id and calendar_date_local columns, these have been defined as entities (and relate to the corresponding dim tables). 
I have 2 derived metrics: metric7 = metric1 + metric2 + metric3 and metric8 = metric4 + metric5 + metric6
I have 1 ratio metric that depends on the 2 derived metrics: metric9 = metric 7 / metric 8

All of the simple metrics have been defined with `fill_nulls_with: 0` and `join_to_timespine: true` based on the [doc](https://docs.getdbt.com/docs/build/fill-nulls-advanced).

When I query all of these metrics together:
```
mf query --metrics metric1,metric2,metric3,metric4,metric5,metric6,metric7,metric8,metric9\
 --group-by calendar_date_local,user_id\
 --order calendar_date_local,user_id
```

What I get is this:
| calendar_date_local   |   user_id |   metric1 |   metric2 |   metric3 |   metric4 |   metric5 |   metric6 |   metric7 |   metric8 |   metric9 |
|:----------------------|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|
| 2024-01-01            |         1 |         1 |         1 |         1 |         0 |         0 |         0 |      3.00 |    nan    |           |
| 2024-01-01            |         2 |         1 |         1 |         1 |         1 |         1 |         1 |      3.00 |      3.00 |      1.00 |
| 2024-01-01            |         3 |         0 |         0 |         0 |         1 |         1 |         1 |    nan    |      3.00 |           |
| 2024-01-02            |         1 |         1 |         1 |         1 |         0 |         0 |         0 |      3.00 |    nan    |           |
| 2024-01-03            |         2 |         0 |         0 |         0 |         1 |         1 |         1 |    nan    |      3.00 |           |

### Expected Behavior

What I would expect is this:
| calendar_date_local   |   user_id |   metric1 |   metric2 |   metric3 |   metric4 |   metric5 |   metric6 |   metric7 |   metric8 |   metric9 |
|:----------------------|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|----------:|
| 2024-01-01            |         1 |         1 |         1 |         1 |         0 |         0 |         0 |      3.00 |    0.00    |     nan      |
| 2024-01-01            |         2 |         1 |         1 |         1 |         1 |         1 |         1 |      3.00 |      3.00 |      1.00 |
| 2024-01-01            |         3 |         0 |         0 |         0 |         1 |         1 |         1 |    0.00    |      3.00 |     0.00   |
| 2024-01-02            |         1 |         1 |         1 |         1 |         0 |         0 |         0 |      3.00 |    0.00    |       nan    |
| 2024-01-03            |         2 |         0 |         0 |         0 |         1 |         1 |         1 |    0.00    |      3.00 |         0.00  |

That is, I would expect the derived metrics to fill nulls with 0 and the ratio metric to return null only if the denominator is 0. 

### Changes needed in compiled SQL

I've also looked into what would have to be changed in the compiled SQL. 
To make it a bit shorter, I've only queried metrics 1, 8 and 9. 

```
mf query --metrics metric1,metric8,metric9\
 --group-by calendar_date_local,user_id\
 --order calendar_date_local,user_id --explain
```

Compiled SQL with commented changes:
```sql
SELECT
  COALESCE(subq_4.calendar_date_local, subq_10.calendar_date_local, subq_24.calendar_date_local) AS calendar_date_local
  , COALESCE(subq_4.user_id, subq_10.user_id, subq_24.user_id) AS user_id
  , COALESCE(MAX(subq_4.metric1), 0) AS metric1
  , COALESCE(MAX(subq_10.metric8), 0) AS metric8 --add coalesce here to make metric8 return the expected result
  , MAX(subq_24.metric9) AS metric9
FROM (
  SELECT
    calendar_date_local
    , user_id
    , COALESCE(sum_of_value1, 0) AS metric1
  FROM (
    SELECT
      calendar_date_local
      , user_id
      , SUM(value1) AS sum_of_value1
    FROM `hive_metastore`.`dbt_silja_mardla_spark`.`semantic1` semantic1_src_10000
    GROUP BY
      calendar_date_local
      , user_id
  ) subq_3
) subq_4
FULL OUTER JOIN (
  SELECT
    calendar_date_local
    , user_id
    , metric4_for_metric8 + metric5_for_metric8 + metric6_for_metric8 AS metric8
  FROM (
    SELECT
      calendar_date_local
      , user_id
      , COALESCE(sum_of_value4, 0) AS metric4_for_metric8
      , COALESCE(sum_of_value5, 0) AS metric5_for_metric8
      , COALESCE(sum_of_value6, 0) AS metric6_for_metric8
    FROM (
      SELECT
        calendar_date_local
        , user_id
        , SUM(value4) AS sum_of_value4
        , SUM(value5) AS sum_of_value5
        , SUM(value6) AS sum_of_value6
      FROM `hive_metastore`.`dbt_silja_mardla_spark`.`semantic2` semantic2_src_10000
      GROUP BY
        calendar_date_local
        , user_id
    ) subq_8
  ) subq_9
) subq_10
ON
  (
    subq_4.calendar_date_local = subq_10.calendar_date_local
  ) AND (
    subq_4.user_id = subq_10.user_id
  )
FULL OUTER JOIN (
  SELECT
    calendar_date_local
    , user_id
    , CAST(metric7_for_metric9 AS DOUBLE) / CAST(NULLIF(metric8_for_metric9, 0) AS DOUBLE) AS metric9
  FROM (
    SELECT
      COALESCE(subq_16.calendar_date_local, subq_22.calendar_date_local) AS calendar_date_local
      , COALESCE(subq_16.user_id, subq_22.user_id) AS user_id
      , COALESCE(MAX(subq_16.metric7_for_metric9),0) AS metric7_for_metric9 --add coalesce here to make metric9 return the expected result
      , COALESCE(MAX(subq_22.metric8_for_metric9),0) AS metric8_for_metric9 --add coalesce here to make metric9 return the expected result
    FROM (
      SELECT
        calendar_date_local
        , user_id
        , metric1_for_metric7 + metric2_for_metric7 + metric3_for_metric7 AS metric7_for_metric9
      FROM (
        SELECT
          calendar_date_local
          , user_id
          , COALESCE(sum_of_value1, 0) AS metric1_for_metric7
          , COALESCE(sum_of_value2, 0) AS metric2_for_metric7
          , COALESCE(sum_of_value3, 0) AS metric3_for_metric7
        FROM (
          SELECT
            calendar_date_local
            , user_id
            , SUM(value1) AS sum_of_value1
            , SUM(value2) AS sum_of_value2
            , SUM(value3) AS sum_of_value3
          FROM `hive_metastore`.`dbt_silja_mardla_spark`.`semantic1` semantic1_src_10000
          GROUP BY
            calendar_date_local
            , user_id
        ) subq_14
      ) subq_15
    ) subq_16
    FULL OUTER JOIN (
      SELECT
        calendar_date_local
        , user_id
        , metric4_for_metric8 + metric5_for_metric8 + metric6_for_metric8 AS metric8_for_metric9
      FROM (
        SELECT
          calendar_date_local
          , user_id
          , COALESCE(sum_of_value4, 0) AS metric4_for_metric8
          , COALESCE(sum_of_value5, 0) AS metric5_for_metric8
          , COALESCE(sum_of_value6, 0) AS metric6_for_metric8
        FROM (
          SELECT
            calendar_date_local
            , user_id
            , SUM(value4) AS sum_of_value4
            , SUM(value5) AS sum_of_value5
            , SUM(value6) AS sum_of_value6
          FROM `hive_metastore`.`dbt_silja_mardla_spark`.`semantic2` semantic2_src_10000
          GROUP BY
            calendar_date_local
            , user_id
        ) subq_20
      ) subq_21
    ) subq_22
    ON
      (
        subq_16.calendar_date_local = subq_22.calendar_date_local
      ) AND (
        subq_16.user_id = subq_22.user_id
      )
    GROUP BY
      COALESCE(subq_16.calendar_date_local, subq_22.calendar_date_local)
      , COALESCE(subq_16.user_id, subq_22.user_id)
  ) subq_23
) subq_24
ON
  (
    COALESCE(subq_4.calendar_date_local, subq_10.calendar_date_local) = subq_24.calendar_date_local
  ) AND (
    COALESCE(subq_4.user_id, subq_10.user_id) = subq_24.user_id
  )
GROUP BY
  COALESCE(subq_4.calendar_date_local, subq_10.calendar_date_local, subq_24.calendar_date_local)
  , COALESCE(subq_4.user_id, subq_10.user_id, subq_24.user_id)
ORDER BY calendar_date_local, user_id
```

### Steps To Reproduce

semantic1.sql
```
            SELECT 1 as id, 1 as user_id, date('2024-01-01') as calendar_date_local, 1 as value1, 1 as value2, 1 as value3
UNION ALL   SELECT 2 as id, 1 as user_id, date('2024-01-02') as calendar_date_local, 1 as value1, 1 as value2, 1 as value3
UNION ALL   SELECT 3 as id, 2 as user_id, date('2024-01-01') as calendar_date_local, 1 as value1, 1 as value2, 1 as value3
```
semantic2.sql
```
            SELECT 1 as id, 2 as user_id, date('2024-01-01') as calendar_date_local, 1 as value4, 1 as value5, 1 as value6
UNION ALL   SELECT 2 as id, 2 as user_id, date('2024-01-03') as calendar_date_local, 1 as value4, 1 as value5, 1 as value6
UNION ALL   SELECT 3 as id, 3 as user_id, date('2024-01-01') as calendar_date_local, 1 as value4, 1 as value5, 1 as value6
```
Semantic models:
```
semantic_models:

  - name: semantic1
    description: ...
    model: ref('semantic1')
    defaults:
      agg_time_dimension: calendar_date_local_dimension
    entities:
      - name: semantic1_id
        expr: id
        type: primary
      - name: calendar_date_local
        type: foreign
      - name: user_id
        type: foreign
    measures:
      - name: sum_of_value1
        expr: value1
        agg: sum
      - name: sum_of_value2
        expr: value2
        agg: sum
      - name: sum_of_value3
        expr: value3
        agg: sum

  - name: semantic2
    description: ...
    model: ref('semantic2')
    defaults:
      agg_time_dimension: calendar_date_local_dimension
    entities:
      - name: semantic2_id
        expr: id
        type: primary
      - name: calendar_date_local
        type: foreign
      - name: user_id
        type: foreign
    measures:
      - name: sum_of_value4
        expr: value4
        agg: sum
      - name: sum_of_value5
        expr: value5
        agg: sum
      - name: sum_of_value6
        expr: value6
        agg: sum
```

Metrics: 
```
metrics:

  - name: metric1
    label: metric1
    type: simple
    type_params:
      measure:
        name: sum_of_value1
        fill_nulls_with: 0
        join_to_timespine: true

  - name: metric2
    label: metric2
    type: simple
    type_params:
      measure:
        name: sum_of_value2
        fill_nulls_with: 0
        join_to_timespine: true

  - name: metric3
    label: metric3
    type: simple
    type_params:
      measure:
        name: sum_of_value3
        fill_nulls_with: 0
        join_to_timespine: true

  - name: metric4
    label: metric4
    type: simple
    type_params:
      measure:
        name: sum_of_value4
        fill_nulls_with: 0
        join_to_timespine: true

  - name: metric5
    label: metric5
    type: simple
    type_params:
      measure:
        name: sum_of_value5
        fill_nulls_with: 0
        join_to_timespine: true

  - name: metric6
    label: metric6
    type: simple
    type_params:
      measure:
        name: sum_of_value6
        fill_nulls_with: 0
        join_to_timespine: true


  - name: metric7
    label: metric7
    type: derived
    type_params:
          expr: metric1_for_metric7 + metric2_for_metric7 + metric3_for_metric7
          metrics:
            - name: metric1
              alias: metric1_for_metric7
            - name: metric2
              alias: metric2_for_metric7
            - name: metric3
              alias: metric3_for_metric7

  - name: metric8
    label: metric8
    type: derived
    type_params:
          expr: metric4_for_metric8 + metric5_for_metric8 + metric6_for_metric8
          metrics:
            - name: metric4
              alias: metric4_for_metric8
            - name: metric5
              alias: metric5_for_metric8
            - name: metric6
              alias: metric6_for_metric8

  - name: metric9
    label: metric9
    type: ratio
    type_params:
      numerator:
        name: metric7
        alias: metric7_for_metric9
      denominator:
        name: metric8
        alias: metric8_for_metric9

```

### Environment

```markdown
- OS: Mac OS
- Python: 3.11
- dbt: 1.7.9
- metricflow: 0.205
```

### Which database are you using?

other (mention it in "Additional Context")

### Additional Context

Databricks
