### ISSUE TITLE
[Feature] Semantic model dimensions should have `type: categorical` as default

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/metricflow#1464]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In semantic models for dimension tables we can have a long list of dimensions. 
Most of these are going to be `type: categorical`. At the moment we need to explicitly specify the type for every single dimension, which is rather tedious (imagine a table with 20+ attributes). 

Example: 
```
semantic_models:
  - name: dim_customer
    model: ref('dim_customer')
    defaults:
      agg_time_dimension: customer_created_date
    dimensions:
      - name: customer_created_date
        type: time
        type_params:
          time_granularity: day
      - name: customer_name
        type: categorical
      - name: customer_type
        type: categorical
```

### Describe alternatives you've considered

Make type: categorical the default and allow omitting this config. 

Example: 
```
semantic_models:
  - name: dim_customer
    model: ref('dim_customer')
    defaults:
      agg_time_dimension: customer_created_date
    dimensions:
      - name: customer_created_date
        type: time
        type_params:
          time_granularity: day
      - name: customer_name       # defaults to categorical
      - name: customer_type         # defaults to categorical
```

### Who will this benefit?

Anyone using MetricFlow

### Are you interested in contributing this feature?

Happy to help with requirements and testing
