### ISSUE TITLE
[SL-3069] Expose a way to disable automatic `date_trunc` on time dimensions

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#1498]
## Summary

MetricFlow will apply a `date_trunc` on time dimensions to make sure they conform the the specified granularity. i.e we will render this SQL for the following dimension `date_trunc('day', data_dt)`

```
- name: data_dt
        type: time
        is_partition: True
        type_params:
          time_granularity: day
```

The issue is that Snowflake, and likely other engines, won't respect partition pruning on `data_dt` if we apply a date trunc function. We need a way to respect partition pruning for time dimension 

## Possible Solutions

We could expose a way to make the date trunc function optional i.e 

```
- name: data_dt
        type: time
        is_partition: True
        type_params:
          time_granularity: day
          enfore_granularity: false #default true 
```

This could lead to some odd behavior with time based joins, where we expect every dimension to conform to the specified grain. The expectation would be that the user makes sure the dimension is add the right grain downstream to guarantee all time based joins will work.

<sub>From [SyncLinear.com](https://synclinear.com) | [SL-3069](https://linear.app/dbt-labs/issue/SL-3069/expose-a-way-to-disable-automatic-date-trunc-on-time-dimensions)</sub>
