### ISSUE TITLE
[Bug] dbt-core properties are not supported in semantic_model.yml and Discovery API

### ISSUE THREAD

**Issue by alenaomal** [dbt-labs/metricflow#1507]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

There was [issue](https://github.com/dbt-labs/metricflow/issues/739) previously, but it was not fully solved.  
**Meta** and **Tags** are not supported in `entities`, `measures`, `dimensions`, but looks like should as per [discussion](https://github.com/dbt-labs/dbt-core/discussions/7456).   
An error occured
` Invalid semantic_models config given in FilePath ... at path ['<entity_name>'][<seq_number>]: Additional properties are not allowed ('<property_name>' was unexpected) `
example
` Invalid semantic_models config given in FilePath ... at path ['entities'][0]: Additional properties are not allowed ('tags' was unexpected)`  
For comparison:
`semantic_models` part supports _config_, and meta and tags can be added there (config was resolution of issue mentioned above).  
`metrics` part supports meta and tags as expected.  
Moreover, these properties are absent in [Discovery API](https://docs.getdbt.com/docs/dbt-cloud-apis/discovery-api) (https://ye912.metadata.us1.dbt.com/graphql) (measure example on the screenshot). (separate feature can be submitted if it was done intentionally)
![image](https://github.com/user-attachments/assets/46ced6ad-2232-4097-9b69-99bd740bcc99)

### Expected Behavior

User is able to use Meta and Tags in semantic_model.yml (entities, measures, dimensions) and accessible via Discovery API.  
```
semantic_models:
  - name: transaction
    model: ref('fact_transaction')
    description: "Our transaction semantic_model. Config supported for semantic_models instead of meta. Meta and tags can be 
 added there"
    default:
        agg_time_dimension: transaction_date
    config:
       meta:
         whatever_key: whatever_value

    entities:
      - name: transaction
        type: primary
        expr: transaction_id
        meta: 
           whatever_key: whatever_value
        tags: ["dev"]

    dimensions:
      - name: transaction_date
        type: time
        type_params:
            time_granularity: day
        meta: 
           whatever_key: whatever_value
        tags: ["dev"]

    measures:
      - name: transaction_total
        description: "The total value of the transaction"
        agg: sum
        meta: 
           whatever_key: whatever_value
        tags: ["dev"]

metrics:
  - name: revenue
    description: "some description. Meta and tags supported for metrics"
    meta: 
       whatever_key: whatever_value
    tags: ["dev"]
    type: simple
    type_params:
        measure: transaction_total
```

### Steps To Reproduce

1. Add Meta or Tags properties to entities, measures or dimensions to semantic_model.yml
2. Run dbt parse
3. Get an error 
` Invalid semantic_models config given in FilePath ... at path ['<entity_name>'][<seq_number>]: Additional properties are not allowed ('<property_name>' was unexpected) `
example
` Invalid semantic_models config given in FilePath ... at path ['entities'][0]: Additional properties are not allowed ('tags' was unexpected)`  

### Environment

```markdown
- OS: Windows 10
- Python: 3.10.8
- dbt:1.8.100
- metricflow:0.7.1
```

### Which database are you using?

bigquery
