### ISSUE TITLE
[Regression] Changes from Meta/Tags to Config properties in semantic_model.yml/semantic_models lead to NULLs in Discovery API query result

### ISSUE THREAD

**Issue by alenaomal** [dbt-labs/metricflow#1508]
### Is this a regression in a recent version of metricflow?

- [X] I believe this is a regression in metricflow functionality
- [X] I have searched the existing issues, and I could not find an existing issue for this regression

### Current Behavior

Hi all! I understand, that this part can be slightly related to metricflow, but I believe that resolution of the following [issue](https://github.com/dbt-labs/metricflow/issues/739) leads to the current state.    
I have semantic_model.yml file with described model and other attributes (just part of it below)
```
semantic_models:
  - name: my_model
    config:
      meta:
        whatever_key: whatever_value
      tags: ["role_developer", "type_test"]
    defaults:
      agg_time_dimension: updated_datetime
    description: some description
    model: ref('sl_my_model')
 ```
 and I want to get meta or tags or whatever using Discovery API.   
 There is possibility to add `meta` and `tags` to API query. But the result is empty.  And there is no possibility to add `config` to query instead. (using https://ye912.metadata.us1.dbt.com/graphql)

![image](https://github.com/user-attachments/assets/ac72ebc9-7034-4847-94c4-7f5031ea7479)

 ```
 {
  "data": {
    "environment": {
      "definition": {
        "semanticModels": {
          "edges": [
            {
              "node": {
                "name": "my_model",
                "meta": null,
                "tags": [],
                "description": "some description"
              }
            }
          ]
        }
      }
    }
  }
}
```

### Expected/Previous Behavior

Discovery API can return all attributes from `config` property for semantic_models.  

### Steps To Reproduce

Way 1.
Go to https://ye912.metadata.us1.dbt.com/graphql and make sure that there is no property config in API.  
Meta and Tags exist in API but they cannot be added directly to yml file, an error occured during validation.
1. Add meta property to semantic_models
```
semantic_models:
  - name: my_model
    meta:
      test: test
    ....
```
2. Run `dbt parse`
3. Get an error
`Invalid semantic_models config given in FilePath(searched_path='models', relative_path='semantic_models\\my_model.yml', ... - at path []: Additional properties are not allowed ('meta' was unexpected)` - if I can't add them to yml, I can't query via API

Way 2.
1. In semantic_model.yml file add property config with meta and/or tags attributes.  
```
semantic_models:
  - name: my_model
    config:
      meta:
        whatever_key: whatever_value
      tags: ["role_developer", "type_test"]
    ....
```
2. Use the following query to get meta and tags from yml using https://ye912.metadata.us1.dbt.com/graphql. (add appropriate `environmentId` and `first` variables)
```
query SemanticModels($environmentId: BigInt!, $first: Int) {
  environment(id: $environmentId) {
    definition {
      semanticModels(first: $first) {
        edges {
          node {
            name
            meta
            tags
            description
          }
        }
      }
    }
  }
}
```
4. Check empty result  
 ```
 {
  "data": {
    "environment": {
      "definition": {
        "semanticModels": {
          "edges": [
            {
              "node": {
                "name": "my_model",
                "meta": null,
                "tags": [],
                "description": "some description"
              }
            }
          ]
        }
      }
    }
  }
}
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.10.8
- metricflow (working version): 0.7.1
- metricflow (regression version): ?
```

### Which database adapter are you using with metricflow?

bigquery
