### ISSUE TITLE
[Feature] Add 'data_type' key to measures and metrics

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/metricflow#1527]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

This is an extension to https://github.com/dbt-labs/metricflow/issues/1287

For downstream usage of measures and metrics to really reduce the workload on the users, it would be great to specify the data type by the owner of the measure or metric.

```
    measures:
      - name: some_monetary_measure
        expr: some_monetary_column
        agg: sum
        data_type: [Optional, would default to no type conversion] decimal(20,2)
```
and
```
metrics:
  - name: some_monetary_metric
    type: simple
    type_params:
      measure: some_monetary_measure
    data_type: [Optional, would pick up on the measure data type if not specified] decimal(20,2)
```

### Describe alternatives you've considered

Sometimes the underlying table does not have the appropriate data type, in this case every downstream user of the metric needs to do the type conversion. 

### Are you interested in contributing this feature?

Happy to test
