### ISSUE TITLE
[Feature] Allow defining aliases for metrics

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/metricflow#1603]
### Is this your first time submitting a feature request?

- [x] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [x] I have searched the existing issues, and I could not find an existing issue for this feature
- [x] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

In a real business environment it happens that we might have multiple widely used names for the same metric. It should be possible to define aliases for metrics so that users could query the metric by either name. For example:
```
metrics:   
  - name: subscription_revenue
    label: Subscription Revenue
    alias: premium_revenue
    alias_label: Premium Revenue
    description: We have a subscription business called "premium", this metric shows the revenue from the subscription a.k.a. premium product
    type: simple
    type_params:
      measure: revenue
```

### Describe alternatives you've considered

Defining one metric and a derived metric on top of that metric, to be able to give the derived metric a different name, although there is no calculation involved. This option would create unnecessary complications in the compiles SQL and inflate the number of metrics in the glossary. 

### Who will this benefit?

All MetricFlow users. 

### Are you interested in contributing this feature?

With testing and feedback, yes
