### ISSUE TITLE
[SL-3391] [Bug] Allow meta in semantic model entities

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/metricflow#1604]
### Is this a new bug in metricflow?

- [x] I believe this is a new bug in metricflow
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

It's a dbt standard that any configurations also take the meta key. In case of semantic model entities, this does not work. 
For example
```
semantic_models:
  - name: dim_city
    description: City dimension
    model: ref('dim_city')
    entities:
      - name: city_id
        type: primary
        meta:
          state: live
      - name: country_id
        type: foreign
```
will result in the following error:
```
Parsing Error
  Invalid semantic_models config given in ... - at path ['entities'][0]: Additional properties are not allowed ('meta' was unexpected)
```

### Expected Behavior

Meta should be supported to enable the governance that dbt usually enables. Sample use cases might include adding business knowledge about the entity, ownership, domains etc. 

### Steps To Reproduce

Try to add a meta key to an existing semantic model. 

### Relevant log output

```shell

```

### Environment

```markdown
- OS:
- Python:
- dbt:
- metricflow:
```

<sub>[SL-3391](https://linear.app/dbt-labs/issue/SL-3391/[bug]-allow-meta-in-semantic-model-entities)</sub>

**Comment by jkillian** [comment]
I believe this might be fixed in https://github.com/dbt-labs/dbt-semantic-interfaces/pull/358. `meta` just needs to be inside a `config` field:

```
semantic_models:
  - name: dim_city
    description: City dimension
    model: ref('dim_city')
    entities:
      - name: city_id
        type: primary
        config:
          meta:
            state: live
      - name: country_id
        type: foreign
```
