### ISSUE TITLE
[Bug] offset_window in metrics use Non-Calendar-Aligned Windowing

### ISSUE THREAD

**Issue by JoseEchave** [dbt-labs/metricflow#1758]
### Is this a new bug in metricflow?

- [x] I believe this is a new bug in metricflow
- [x] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When using a derived or cumulative metric with a month-based offset_window (e.g., "1 month"), the SQL generated by MetricFlow to fetch data from the offset month can undercount aggregations like SUM or COUNT DISTINCT. 

This happens if the offset calendar month has more days than the month providing the daily iteration for the offset join in the SQL (e.g., current query context is April with 30 days, offset month is March with 31 days). The generated join logic, which appears to be ON DATEADD(month, -N, time_spine_day_in_current_month) = event_table_event_date_in_offset_month, fails to include events from the "extra" days (e.g., the 31st) of the longer offset month.
For example, when calculating a 3-month trailing sum for April 2025, the component for March 2025 (via offset_window: "1 month") incorrectly omitted 114 events that occurred on March 31st, leading to an inaccurate trailing sum. This occurs even if the input metric to the offset_window is itself a metric that correctly represents a full calendar month's total.

### Expected Behavior

When using offset_window: "N months" in a derived metric that is grouped by month, it's expected that the offset component will retrieve the complete and accurate aggregated value of the input metric for the Nth prior full calendar month.
For instance, if the current query context is April 2025 and a derived metric uses an input with offset_window: "1 month", this component should resolve to the total value of the input metric for the entire calendar month of March 2025, including data from all days of March (e.g., March 1st to March 31st).

### Steps To Reproduce

Semantic Model (e.g., sm_example.yml):
Define a semantic model on a table with event data (event_id, event_date).
```
    semantic_models:
      - name: example_event_source
        model: ref('example_events_table') # Contains event_id, event_date
        defaults:
          agg_time_dimension: event_date
        entities:
          - name: event_entity
            type: primary
            expr: event_id
        dimensions:
          - name: event_date
            type: time
            expr: event_date
            type_params:
              time_granularity: day
        measures:
          - name: event_row_count
            description: "Count of events by summing rows."
            agg: sum
            expr: 1
```
Metrics Definition (e.g., metrics_example.yml):
Define a metric for the monthly event count, and a derived metric for a 3-month sum using this monthly metric with offsets.

```
    metrics:
      - name: monthly_event_count
        label: "Monthly Event Count"
        type: simple # Or a cumulative with grain_to_date: "month", period_agg: "last"
        type_params:
          measure: event_row_count

      - name: event_sum_trailing_3m_derived
        label: "Event Sum Trailing 3M (Derived)"
        type: derived
        type_params:
          expr: m0 + m1 + m2
          metrics:
            - name: monthly_event_count
              alias: m0
            - name: monthly_event_count
              alias: m1
              offset_window: "1 month"
            - name: monthly_event_count
              alias: m2
              offset_window: "2 months"
````
**Data:**
Populate example_events_table such that:
* February 2025 has 885 events.
* March 2025 has 1114 events, with exactly 114 of these occurring on March 31st, 2025.
* April 2025 has 1104 events.
Run Query:
`mf query --metrics monthly_event_count,event_sum_trailing_3m_derived --group-by metric_time__month --start-time='2025-04-01' --end-time='2025-04-30'`
**See error/discrepancy:**
For metric_time__month = 2025-04-01 (April):
monthly_event_count will correctly show 1104.
event_sum_trailing_3m_derived will show 2989.
The expected value for event_sum_trailing_3m_derived is 1104 (Apr) + 1114 (Mar) + 885 (Feb) = 3103.
The discrepancy (3103 - 2989 = 114) matches the count of events on March 31st, which are missed by the offset_window: "1 month" calculation.

### Relevant log output

```shell
The SQL generated by mf query ... --explain for the offset_window: "1 month" component (calculating m1 for April, which should represent March's total) shows a join logic similar to:
-- Simplified problematic part for m1 (March total from April context)
SELECT
  time_spine_current_month.month_start AS metric_time__month,
  SUM(events_previous_month.value_column_representing_1) AS m1
FROM time_spine_table time_spine_current_month -- Iterates days of April (1st to 30th)
INNER JOIN
  event_data_table events_previous_month
ON
  -- This join connects each day in April to a day in March
  DATEADD(month, -1, time_spine_current_month.day) = events_previous_month.event_date
WHERE time_spine_current_month.month_start = '2025-04-01'
GROUP BY
  time_spine_current_month.month_start;

This join, when time_spine_current_month.day iterates from April 1st to April 30th, means DATEADD(month, -1, time_spine_current_month.day) will range from March 1st to March 30th. It does not create a condition to include events_previous_month.event_date = '2025-03-31', thus missing data from March 31st.
```

### Environment

```markdown
- OS: 3.12
- Python: 3.12.6
- dbt: 1.9.4
- metricflow: 0.8.2
```

### Which database are you using?

snowflake

### Additional Context

Using cumulative metrics instead of derived metrics results in similar issue.
