### ISSUE TITLE
[SL-1316] Support a "time spine" aggregation time dimension type

### ISSUE THREAD

**Issue by tlento** [dbt-labs/metricflow#319]
**Describe the Feature**
Currently, all aggregations assume that every input row has a point in time value attached to it, and that all time values of interest are represented in the input data source.

This assumption is extremely limiting. If someone defines a measure on a dimension data source with a validity window set (i.e., an SCD Type II layout), every row - either implicitly or explicitly - is mapped to a range of points in time, rather than a singular point in time, and any measure that does a simple linear aggregation against one or the other endpoint of that range will produce incorrect results.

This goes beyond SCD Type II data sources. Consider the listings_latest data source in the simple model we use for our integration tests: https://github.com/transform-data/metricflow/blob/main/metricflow/test/fixtures/model_yamls/simple_model/data_sources/listings_latest.yaml#L24

The `primary_time` is mapped to the `created_at` column, but the underlying table is in fact a snapshot of the current - as of today - set of listings in the database.

This means any count that joins primary times together, such as we might get in a derived metric scenario, will systematically omit listings which should rightly be counted. The `listings` measure in that data source, then is actually a measure of `listings created on date x`, not `listings in existence on the date of interest`.

Our proposal for fixing both of these problems is to add a feature that allows users to define the aggregation time dimension for any measure as a `time_spine` with a start and end window.

As an example, having a "time spine" type would let us do something like the following for listings_latest:

```
---
data_source:
  name: listings_latest

  sql_table: default.listings_latest

  measures:
    - name: listings
      expr: 1
      agg: sum
      agg_time_dimension:
        dimension: time_spine
        start_time: date_added
        end_time: date_removed

  dimensions:
    - name: date_added
      type: time
      expr: created_at
      type_params:
        time_granularity: day
    - name: date_removed
      type: time
      expr: COALESCE(removed_time, CURRENT_DATE())
      type_params:
        time_granularity: day
```

Someone running a query that requests the `listings` measure would then be doing, essentially:

```
SELECT spine.ds AS metric_time, SUM(1) AS listings
FROM spine_tables.time_spine_daily AS spine
LEFT OUTER JOIN default.listings AS listings
ON spine.ds >= listings.created_at AND spine.ds < COALESCE(listings.removed_time, CURRENT_DATE())
GROUP BY 1
```

For data sources defined using the SCD syntax described in #276 the `primary_time` would be effectively fixed to the validity window. However, users would not need to define a validity window to use this - they could make use of a time spine in an ad hoc manner on a measure-by-measure basis if they should happen to have a table describing, e.g., time-bound state changes within a row (such as a table with a primary key of `application_id` with a trio of dates for `submitted_on`, `reviewed_on`, and `closed_on` state updates).

This change, as described, would require us to mark `time_spine` as a reserved keyword.

<sub>[SL-1316](https://linear.app/dbt-labs/issue/SL-1316/support-a-time-spine-aggregation-time-dimension-type)</sub>

**Comment by nhandel** [comment]
It's also important that this isn't a breaking change. Today `agg_time_dimension` takes a time column as an input. This will add a struct format. Both should still be accepted inputs. We should map time_spine in the following way:

```
agg_time_dimension: my_time_dim
```
is equivalent to:
```
agg_time_dimension: 
  dimension: my_time_dim
  start_time: my_time_dim
  end_time: my_time_dim
```

and, 

```
agg_time_dimension: time_spine
```
is equivalent to:
```
agg_time_dimension: 
  dimension: time_spine
  start_time: primary_time # or the time dim with window_start: True for an SCD table
  end_time: primary_time # or the time dim with window_end: True for an SCD table
```

Ideally, people are not interacting with this struct 99% of the time, but they have fine-grained control if they want to dive in.

**Comment by tlento** [comment]
Good call out on backwards compatibility. This is NOT a breaking change as far as the model is concerned.

Regarding this:

```
agg_time_dimension: 
  dimension: time_spine
  start_time: primary_time # or the time dim with window_start: True for an SCD table
  end_time: primary_time # or the time dim with window_end: True for an SCD table
```

This behavior is pretty subtle if it's not explicitly spelled out. For the non-SCD case what this essentially says is "aggregate on primary time but null pad any missing time periods." It's not all that useful in the metric definition at that point, although if we add support overrides for that null value it'll be pretty important. We might want to require all time_spine uses to define the target of the spine join for now just for clarity for people reading the model.

In any case, it looks like we are not going to support this scenario initially - the two dimension case is much easier for us to render at the moment - so we've got a bit of time to decide. And we can always validate for a bit and ease up if it's burdensome.
