### ISSUE TITLE
Cumulative mesure or metric for categorical dimension (accessed via a join)

### ISSUE THREAD

**Issue by vviers** [dbt-labs/metricflow#345]
# Describe the Feature
Say I have 2 tables

### `hr_data`

| departement | employees |
|:------:|:------------:|
|  1  | 150 |
|  2 | 100 |
|  3 | 50 |
| 4 | 25 |
|  5 | 0 |
|  6 | 70 |

### `geographic_referential`

| region | departement |
|:------:|:------------:|
| A | 1  |
| A | 2 |
| A | 3 |
| B | 4 |
| C | 5 |
| C | 6 |

(`departement` is a primary key in both tables, region is a foreign key)

**I would like to be able to compute a metric that's the proportion of employees in a departement over the employee total in the corresponding region**. Something that would look like :

| departement | employees | employees_total_in_region | proportion_of_region_total |
|:------:|:------------:|:------------:|:------------:|
|  1  | 150 | 200 | .75 |
|  2 | 100 | 200 | .5 |
|  3 | 50 | 200 | .25 |
| 4 | 25 | 25 | 1 |
|  5 | 0 | 70 | 0 |
|  6 | 70 | 70 | 1 |

I'm fairly new to MetricFlow (and really liking it btw!), but after hours of trying I could not find a way to do this.

**Would you like to contribute?**
Are you interested in building this feature?
👉🏼  yes absolutely, though I would need some guidance on how you think is the best way to implement this. Maybe a new measure or metrics type(s) ?

**Anything Else?**

Here's what I tried : 

```yaml
data_source:
  name: geo
  description: french geographic data
  owners:
    - me@gouv.fr
  identifiers:
    - name: departement
      type: primary
    - name: region
      type: foreign # this will be accessible as a dimension too
  dimensions:
    - name: annee
      description: the current year # (metricflow is forcing us to define a time dimension, which makes sense)
      type: time
      expr: TO_DATE('2022', 'YYYY')
      type_params:
        is_primary: True
        time_granularity: year

  sql_table: public.geographic_referential
  mutability:
    type: immutable
    
---

data_source:
  name: hr
  description: hr data
  owners:
    - me@gouv.fr
  identifiers:
    - name: departement
      type: primary
  dimensions:
    - name: annee
      description: the current year # (metricflow is forcing us to define a time dimension, which makes sense)
      type: time
      expr: TO_DATE('2022', 'YYYY')
      type_params:
        is_primary: True
        time_granularity: year
  measures:
    - name: employees
      description: number of employees in the departement
      agg: SUM
      create_metric: true
   - name: employees_total_in_region
     description: number of employees in the region
     expr: SUM(employees) OVER departement__region # this does not work...
     agg: SUM
     create_metric: true

  sql_table: public.hr
  mutability:
    type: full_mutation

---

---
metric:
  name: proportion_of_region_total
  owners:
    - me@gouv.fr
  type: ratio
  type_params:
    numerator: employees
    denominator: employees_total_in_region
```

I tried many different ways with no success, am I missing something obvious here ?

**Comment by nhandel** [comment]
Great feature request! Thanks for the examples too. I've heard this called a "composition ratio" or "mix percentage" before. Unfortunately, I don't think it's possible yet so thank you for opening an issue.

In terms of deciding where this should go. We have a few rules of thumb:
**Measures** - Anything related to how the aggregation is accomplished. With the exception of the aggregation time dimension (`agg_time_dimension`) we avoid mixing measures and dimensions.
**Metrics** - Compositions of measures and dimensions that you want to lock in as a definition for a metric. 
**Querying Interface** - Anything that needs to be dynamic. 

A few thoughts on this metric:

- Defining this in the configs makes sense. I can see a user wanting to define a composition ratio metric statically and/or dynamically so I can see it existing in the metric definition or in the query interface. It sounds like you would like to define this statically in the metric definition (see idea below)
- A user you might want the composition ratio of a metric to be defined in relation to different dimensions in different circumstances. This is a bit more complicated, but composition ratios are fairly common so maybe we can add a way to create a composition ratio from an existing metric (something like this syntax which doesn't exist yet but we've talked about: `employees.composition_ratio(region)`)

```
metric:
  name: proportion_of_region_total
  owners:
    - me@gouv.fr
  type: ratio
  type_params:
    numerator: # note this nested syntax already exists for adding constraints
      name: employees
      group_by_dimension: departement__region
      alias: employees_by_region
    denominator: employees
```

A few questions as we think through how to design this: 
- If you just request `proportion_of_region_total` with no `department` dimension what would you expect to happen?
- Would you want a more generic `employee_proportion` that you could cut by any dimension? i.e. `employee_proportion BY employee__type` would return proportions by `employee__type` OR would you want a more generic `employees` metric where you apply a proportion modifier and group by department?

One other small not on your configs - You only have to define a date for a table with a measure. You can use the CURRENT_DATE() function in some warehouses to more easily keep that updated in your code.
