### ISSUE TITLE
String indicators in measures and metrics ?

### ISSUE THREAD

**Issue by vviers** [dbt-labs/metricflow#360]
Hey there 👋🏼 

A couple of us data peeps working for the french administration are looking into different open "metrics-schema" standards in order to implement some sort of metrics store. We're really liking the MetricFlow standard and we're trying to figure out what is currently missing and needs to be added (e.g. #345 ) before deciding whether to commit to your standard in building our metric store. Again, thanks for the great (open) work which is very valuable to us 💯 

## Describe the Feature

Say we're interested in measuring how well a government program is rolled out across french cities. Our users are interested in two indicators / metrics : 
1. **How many** cities are benefiting from the program in each region at a given date ? (an integer)
1. **Which** cities are benefiting from the program in each region at a given date ? (a list of strings)

Now, 1. is obviously very easy to define using the MetricFlow framework, but 2. is (to the best of my knowledge) outside the scope of what MetricFlow defines as a metric.

From a product philosophy standpoint, do you think that a (list of) string(s) can be thought of as a metric ? (We would say so, but happy to get the discussion started)

I don't want to jump to implementations details before discussing it with you firsthand, but something that would be super useful to us could be :
- figuring out a way to get the detailed values breakdown (as some sort of metadata) when querying a measure that has the `count_distinct` aggregation type
- creating a new aggregation (`list_distinct` ?) for measures defined over a column of type string ?

## Would you like to contribute?
Yes, if we get your go ahead.

## Anything Else?
Happy to set up a call with your team if you think it's easier to talk it over the phone :)

cc @yohanboniface

**Comment by tlento** [comment]
Hi @vviers !

Thanks for the input, we very much appreciate your engagement here! The short answer is I think your first approach fits best with Metricflow's model, and it's something that's been on our radar but we haven't been prioritizing. If you're interested in working on this we'd love to collaborate!

Our mental model of this is that measures and metrics are always numeric. What I keep telling myself is a measure is something that can be aggregated into a metric, and a metric is something that can be plotted against time.

In MetricFlow terms, when your users request the list of cities benefiting from a program, they are asking for a filtered set of dimension values (`city names`) associated with a metric input (`did benefit`, possibly defined as a threshold against some magnitude). We have partial support for this (see below), and we have received requests for more robust queries against dimension sets. Ideally you'd be able to define `city_name` as a dimension and `saw_benefit` as a separate model field and then be able to run a query like:

`mf get-dimension-values --dimension-name city_name --constraint saw_benefit`

This doesn't work today, because dimensions currently are only reachable from a metric as a starting point, and custom constraints are not supported for `get-dimension-values`, only time constraints (which might be sufficient for your immediate needs). You can work around this, but only if the data source and metric definitions pre-filter to the dimension value subset of interest. It'd look something like this:

```
data_source:
  # data source details here, where the saw_improvement boolean would be pre-computed
  measures:
    - name: improvement_count
      agg: sum
      expr: "IF(saw_improvement, 1, 0)"
    - name: num_cities
      agg: count_distinct
  dimensions:
    - name: assessment_date
      # primary time dimension params here
    - name: city_name
      type: categorical
    - name: saw_improvement
      type: categorical

---
metric:
  name: num_cities_benefiting
  measures:
    - name: num_cities
      constraint: saw_improvement

---
metric: 
  name: non_zero_improvement_counts
  measures:
    - name: improvement_count
      constraint: saw_improvement
```

Then you can query for `num_cities_benefiting` directly for your first scenario, and run something like `mf get-dimension-values --metric-name non_zero_improvement_counts --dimension-name city_name`, and you can filter on `assessment_date` by passing in time constraint ranges to the `get-dimension-values` query.

Of course, this model is burdensome if you want to support a variety of different constraints, because all of those dimension markers would have to be pre-computed.
