### ISSUE TITLE
dbt to metricflow conversion fails if a data source has multiple time dimensions

### ISSUE THREAD

**Issue by stefano-sequence** [dbt-labs/metricflow#433]
**Describe the bug**
Say a dbt model has 2 possible timestamp columns (e.g. "created_at" and "updated_at"), and 2 dbt metrics are built on top of that model each using one of the 2 timestamp columns. This currently breaks the dbt -> metricflow conversion logic [here](https://github.com/transform-data/metricflow/blob/e56a95824c7399c2d30050014b38938944f9dd4e/metricflow/model/transformations/dbt_to_metricflow.py#L359) (this line assumes that each `dbt_metric.model` has a unique `dbt_metric.timestamp`

**Steps To Reproduce**
```
-- test_model.sql
SELECT CURRENT_DATE() AS created_at,
    CURRENT_DATE() AS updated_at,
    1.0 AS x
```
```
# schema.yml
version: 2

metrics:
  - name: test_metric_by_created_at
    label: Metric by created at
    model: ref('test_model')
    calculation_method: sum
    expression: x
    timestamp: created_at
    time_grains: [day]
  - name: test_metric_by_updated_at
    label: Metric by updated at
    model: ref('test_model')
    calculation_method: sum
    expression: x
    timestamp: updated_at
    time_grains: [day]
```

```
mf query --metrics test_metric_by_created_at

# File "/opt/homebrew/lib/python3.9/site-packages/metricflow/model/transformations/dbt_to_metricflow.py", line 359, in collect_time_dimension_stats
# time_stats_for_metric_models[dbt_metric.model][dbt_metric.timestamp] += 1
# KeyError: 'created_at'
```

**Expected behavior**
Should work.

**Environment (please complete the following information):**

- MetricFlow Version 0.140.0 (installed from source)
- dbt version: 1.4.4
