### ISSUE TITLE
Create a custom aggregation type for measures

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/metricflow#473]
**Describe the Feature**
A community member suggested that we add a custom aggregation method for aggregation types that we don't support. I have to imagine there are some concerns with testing & validation but I figured I'd create a FR here for folks to discuss!

Here is the proposed design:
```
- name: std_dev_transaction_amount
  description: "The Standard Deviation of the transaction total price"
  agg: custom
  agg_params:
     - sql: stddev( expr )
  expr: transaction_total
```

**Would you like to contribute?**
We shall see. Tom and Paul will probably have the best knowledge on whether this is possible or something we want to consider!
