### ISSUE TITLE
[Bug] Remove expr & ratio metrics and bundle with derived metrics

### ISSUE THREAD

**Issue by callum-mcdata** [dbt-labs/metricflow#504]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

While doing some testing, I came across this bug. It appears that derived metrics require that the `metrics` property of `MetricTypeParams` have `name` defined for each component. I understand this might be necessary when including additional properties of the metric but we should also allow the baseline name of a single metric.

**Valid**:
```yml
metric:
  name: derived_metric
  type: derived
  type_params:
    expr: revenue + customers_7d
    metrics:
      - name: revenue_usd
      - name: customers_7d
```

**Invalid**:
```yml
metric:
  name: derived_metric
  type: derived
  type_params:
    expr: revenue + customers_7d
    metrics:
      - revenue_usd
      - customers_7d
```

### Expected Behavior

The second example working.

### Steps To Reproduce

Metricflow 0.14

### Environment

```markdown
- OS:
- Python:
- dbt:
- metricflow:
```
