### ISSUE TITLE
[Feature] Rename Metric.constraint to Metric.filter

### ISSUE THREAD

**Issue by plypaul** [dbt-labs/metricflow#511]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

### Describe the feature

When defining a metric in the YAML configuration file, the `constraint` field is currently used to specify the filter:

```
metric:
  name: "instant_booking_value"
  description: "booking value of instant bookings"
  type: measure_proxy
  type_params:
    measures:
      - booking_value
  constraint: "{{ dimension('is_instant') }}"
```

To be in line with the latest proposal, it should be named `filter`:

```
metric:
  name: "instant_booking_value"
  description: "booking value of instant bookings"
  type: measure_proxy
  type_params:
    measures:
      - booking_value
  filter: "{{ dimension('is_instant') }}"
```
