### ISSUE TITLE
Measures aren’t respecting `defualt: agg_time_dimension:`

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#603]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have a semantic model defined as:
```
semantic_models:
  #The name of the semantic model.
  - name: orders
    description: |
      Model containting order data. The grain of the table is the order id.
    #The name of the dbt model and schema
    model: ref('orders')
    defaults:
      agg_time_dimension: ds
    #Entities. These usually corespond to keys in the table.
    entities:
      ...
    #Measures. These are the aggregations on the columns in the table.
    measures:
      - name: order_total
        agg: sum
        create_metric: True
```

If I try to run a query I get the following error message: `Aggregation time dimension for measure order_total is not set! This should either be set directly on the measure specification in the model, or else defaulted to the primary time dimension in the data source containing the measure.`

### Expected Behavior

The default agg_time_dimension: ds should be applied to the measure.

### Steps To Reproduce

Create a semantic model with a default agg time dimension and no agg time dimensions specified on a model and try to run a query through the jdbc.

### Environment

```markdown
- OS:
- Python:
- dbt:
- metricflow:
```
