### ISSUE TITLE
[Bug] Derived metric offset at yearly granularity returns no results in BQ

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#725]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Say I have a derived metric defined as follow:
```
 name: total_users_yoy_pct_change
    label: Total Users YoY % Change
    type: derived
    type_params:
      expr: (total_users - total_users_prev_year)*100/total_users_prev_year
      metrics:
        - name: total_users
        - name: total_users
          offset_window: 1 year
          alias: total_users_prev_year
```

When I run `mf query --metrics total_users_yoy_pct_change --group-by metric_time__year` I get no results. This is because BigQuery is using ISOYEAR to truncate metric time to year. A quick primer on isoyear; isoyears start on the first Monday of each year. So `DATE_TRUNC(cast('2023-08-01' as datetime), isoyear)`  will return 2023-01-02 and `DATE_TRUNC(cast('2022-08-01' as datetime), isoyear)` will return 2022-01-03. You can see this behavior in the following subquery:

```
(
      SELECT
        metric_time__year
        , COUNT(DISTINCT total_users) AS total_users_prev_year
      FROM (
        SELECT
          **DATE_TRUNC(cast(date as datetime), isoyear) AS metric_time__year**
          , visitor_id AS total_users
        FROM `inq-warehouse`.`dbt_test`.`fct_sessions` sessions_src_0
      ) subq_7
      GROUP BY
        metric_time__year
    ) subq_9
```
The two offset subqueries used to calculate the derived metric are joined via `DATE_SUB(CAST(subq_10.metric_time__year AS DATETIME), INTERVAL 1 year) = subq_9.metric_time__year.` However, subtracting 1 year from a isodate-truncated date, will not give you the isodate-truncated date of the previous year. You can see this behavior in the following example. The join condition MetricFlow renders would compare 2022-01-02 to 2022-01-03. There are no records that match this equality, so we return no results. 
<img width="761" alt="Screenshot 2023-08-15 at 9 19 43 AM" src="https://github.com/dbt-labs/metricflow/assets/26796796/1ee300a2-6252-48d8-b680-95fea40cac74">

### Expected Behavior

I would expect the metric value from the previous year to be properly joined. If we use `year` instead of `isoyear` as the date type to truncate metric_time, this join would resolve correctly. 

### Steps To Reproduce

1. Check out jaffle-sl-template and update your profile to Bigquery
2. Update the `revenue_growth_mom` query to a year over year comparisom
```
  - name: revenue_growth_yoy
    description: "Percentage growth of revenue compared to 1 year ago. Excluded tax"
    type: derived
    label: Revenue Growth % Y/Y
    type_params:
      expr: (current_revenue - revenue_prev_year)*100/revenue_prev_year
      metrics:
        - name: revenue
          alias: current_revenue
        - name: revenue
          offset_window: 1 year
          alias: revenue_prev_year
```
3. Cast ordered_at to datetime
```
      - name: ordered_at
        expr: cast(ordered_at as datetime)
        type: time
        type_params:
          time_granularity: day
```
4. Run `mf query --metrics revenue_growth_yoy --group-by metric_time__year` and observe that no results are returned.
<img width="714" alt="Screenshot 2023-08-15 at 9 43 18 AM" src="https://github.com/dbt-labs/metricflow/assets/26796796/11c10781-7190-4f36-9707-9257588e1224">

When I run the same query in snowflake i get the following result:
<img width="503" alt="Screenshot 2023-08-15 at 9 42 54 AM" src="https://github.com/dbt-labs/metricflow/assets/26796796/64374a7b-1839-4a33-879f-32b950183977">

### Environment

```markdown
- OS:
- Python:
- dbt:
- metricflow:
```
