### ISSUE TITLE
[SL-1294] [Bug] Multiple derived metrics that depend on the same upstream metric can result in ambiguous SQL code error

### ISSUE THREAD

**Issue by siljamardla** [dbt-labs/metricflow#757]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I have two derived metrics that both depend on an upstream metric called price_before_discounts:
```
  - name: user_discounts
    type: derived
    type_params:
          expr: price_before_discounts - price_after_discounts
          metrics:
            - name: price_before_discounts
            - name: price_after_discounts
  - name: asp_before_discounts
    type: derived
    type_params:
          expr: price_before_discounts / orders_finished
          metrics:
            - name: price_before_discounts
            - name: orders_finished
```
Trying to query them together

```
mf query --metrics user_discounts,asp_before_discounts
```
results in 

```
ERROR: Runtime Error
  Reference 'price_before_discounts' is ambiguous, could be: subq_6.price_before_discounts, subq_6.price_before_discounts.; line 3 pos 2

```
The error makes sense because the compiled SQL code is indeed ambiguous:

```
SELECT
  price_before_discounts - price_after_discounts AS user_discounts
  , price_before_discounts / orders_finished AS asp_before_discounts
FROM (
  SELECT
    SUM(price_before_discounts) AS price_before_discounts
    , SUM(price_after_discounts) AS price_after_discounts
    , SUM(price_before_discounts) AS price_before_discounts
    , COUNT(DISTINCT orders_in_order_try) AS orders_finished
  FROM (
    SELECT
      state AS order_try_key__state
      , order_key AS orders_in_order_try
      , ride_price_eur
      , price_eur
    FROM ... order_tries_src_2
  ) subq_2
  WHERE order_try_key__state = 'finished'
) subq_6

```

### Expected Behavior

As both of these derived metrics seem like reasonable metrics to calculate and I don't see any other way of defining them, I would expect the query to work. That is, the MetricFlow query output should be unambiguous.

### Steps To Reproduce

If you need, I can share the full semantic model and metrics setup privately. 

### Environment

```markdown
- OS: Mac
- Python: 3.11.2
- dbt: 1.6.1
- metricflow: 0.201.0
```

### Which database are you using?

other (mention it in "Additional Context")

### Additional Context

Databricks

<sub>[SL-1294](https://linear.app/dbt-labs/issue/SL-1294/[bug]-multiple-derived-metrics-that-depend-on-the-same-upstream-metric)</sub>

**Comment by Jstein77** [comment]
Thanks for submitting the Issue Silja! I think this is a gap in our validation. We should warn you that this might cause an ambiguous reference in the compiled SQL. Can you try providing an [alias](https://docs.getdbt.com/docs/build/derived) for `price_before_discounts` in one of these metrics? I added an example below.

```
    type_params:
          expr: price_before_discounts - price_after_discounts
          metrics:
            - name: price_before_discounts
            - name: price_after_discounts
              alias: user_price_before_discount
 ```

**Comment by jcberk** [comment]
Is there a reason the user should need to do the disambiguation? I could imagine generating SQL for any non-aliased metrics like:

```
SELECT
  user_discounts__price_before_discounts - user_discounts__price_after_discounts AS user_discounts
  , asp_before_discounts__price_before_discounts / asp_before_discounts__orders_finished AS asp_before_discounts
FROM (
  SELECT
    SUM(price_before_discounts) AS user_discounts__price_before_discounts
    , SUM(price_after_discounts) AS user_discounts__price_after_discounts
    , SUM(price_before_discounts) AS asp_before_discounts__price_before_discounts
    , COUNT(DISTINCT orders_in_order_try) AS asp_before_discounts__orders_finished
...
```

Those are long identifiers, which might cause trouble. And that would get worse if [Support 2-step aggregation for metrics](https://github.com/dbt-labs/metricflow/issues/653) is completed. Maybe problems could trigger an error asking the user to do the aliasing as a fallback.

**Comment by jcberk** [comment]
Alternately, is there a reason to twice compute the component metric at all? Maybe that's a planned optimization already?

**Comment by siljamardla** [comment]
> Thanks for submitting the issue Silja! I think this is a gap in our validation. We should warn you that this might cause an ambiguous reference in the compiled SQL. Can you try providing an [alias](https://docs.getdbt.com/docs/build/derived) for `price_before_discounts` in one of these metrics? I added an example below.
> 
> ```
>     type_params:
>           expr: price_before_discounts - price_after_discounts
>           metrics:
>             - name: price_before_discounts
>             - name: price_after_discounts
>               alias: user_price_before_discount
> ```

For future reference, if a metric is aliased like this, the expression needs to use the alias. This should work:
```
    type_params:
          expr: user_price_before_discount - price_after_discounts
          metrics:
            - name: price_before_discounts
            - name: price_after_discounts
              alias: user_price_before_discount
```
