### ISSUE TITLE
[SL-915] [Feature] Support Saved Queries

### ISSUE THREAD

**Issue by Jstein77** [dbt-labs/metricflow#765]
MetricFlow should have a saved query construct. Saved queries extend governance beyond the semantic objects (metrics, dimensions, and entities) to their consumption by enabling users to pre-define a query in a governed format (yaml/git) and then reference it in downstream interfaces. This construct will use the same structure as the existing querying interface in the Metricflow CLI:  metrics, group_bys, a where clause, limit, and order. Saved queries should be referenceable through semantic layer APIs, including by orchestration in dbt cloud for exports and caching. 

In Cloud, Saved queries are the foundation for supporting exports and a declarative cache. Exports will allow users to write the results of saved queries back to their data warehouse. Exports would be a set of configurations you apply to a saved query that defines how the query should be executed, including destination, materialization strategy, and table name.

### **Saved Query Design**

The saved query should provide a matching interface to the query interfaces used in all other APIs but in YAML form. I’m in favor of nesting these fields into a sub-param called `query` as shown below:

```
saved_queries:
  - name: my_query
    description:
    query:
      metrics:
        -
      group_bys:
        -
      where:
      limit:
      order:
```

<sub>From [SyncLinear.com](https://synclinear.com) | [SL-915](https://linear.app/dbt-labs/issue/SL-915/[feature]-support-saved-queries-in-metricflow)</sub>

**Comment by Jstein77** [comment]
Should we even include the exports section at the bottom? I don't see a benefit to posting it in MetricFlow

**Comment by QMalcolm** [comment]
@Jstein77 what is a the shape of the `metrics` list elements? Should this be the same as `metrics` on metric type params? For clarity the shape of `metrics` elements for metric type params can be specified in two ways:
```YAML
metrics:
  - my_metric
     ...
     type_params:
       ...
       metrics:
         - other_metric
         - name: other_other_metric
           alias: <optional_alias>
           filter: <optional_filter>
           offset_window: <optional_offset_window>
           offset_to_grain: <optional_offset_to_grain>
```

Some separate questions:

- What is the shape of `group_bys`? I don't believe there is an existing example
- Is `where` a different name for the existing `filter` spec?
- Is order supposed to be a `measure` / `dimension`? Does it allow for `ASC` / `DESC` specification?

**Comment by nhandel** [comment]
@QMalcolm This is a bit simpler than the `derived` metric type metric list. We just need a list of strings here similar to the structure we use in our query inputs. As an example, the following query from the CLI:

```
mf query --metrics "users, revenue" --group-by "metric_time__day,Dimension('signup_at').grain('month')" --where Dimension('user__is_active')
```

would become this saved query:

```
saved_queries:
  - name: key_metrics_by_signup_month
    description: Key metrics grouped by the users signup month
    query:
      metrics:
        - users
        - revenue
      group_bys:
        - metric_time__day
        - Dimension('signup_at').grain('month')
      where: Dimension('user__is_active')
```
