### ISSUE TITLE
[Bug] --start-time / --end-time with cumulative windows broken 

### ISSUE THREAD

**Issue by ernestoongaro** [dbt-labs/metricflow#869]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

these two metrics:
``` 
 - name: cumulative_orders_one_week
    label: 1 week   
    type: cumulative
    type_params:
      measure: order_total
      window: 1 week
```
and
```
  - name: cumulative_orders_seven_days
    label: 7 days   
    type: cumulative
    type_params:
      measure: order_total
      window: 7 days
```
when we pass in `--start-time` and `--end-time`  only the one with window `7 days` is giving correct SQL generated

here's a diff of the two queries, the one on the left is filtering the time frame correctly, the one on the right is ignoring it
<img width="1496" alt="Pasted Graphic 1" src="https://github.com/dbt-labs/metricflow/assets/47784/19a8342c-4276-4f7a-8d16-bb2675505de5">

### Expected Behavior

Expect 1 week and 7 days windows to behave similarly 

### Steps To Reproduce

1. in `dbt jaffle sample` add these two metrics to the bottom of orders.yml

```
  - name: cumulative_orders_one_week
    label: 1 week   
    type: cumulative
    type_params:
      measure: order_total
      window: 1 week
  - name: cumulative_orders_seven_days
    label: 7 days   
    type: cumulative
    type_params:
      measure: order_total
      window: 7 days
```

run 
``` 
mf query --metrics cumulative_orders_one_week --group-by metric_time --start-time 2023-11-12 --end-time 2023-11-12 --explain
```
and
```
 mf query --metrics cumulative_orders_seven_days --group-by metric_time --start-time 2023-11-12 --end-time 2023-11-12 --explain
````

### Environment

```markdown
- OS: Mac
- Python: 3.9.6
- dbt: 1.7.1
- metricflow: 0.203.0
```

### Which database are you using?

bigquery

### Additional Context

Only tested on dbt-bigquery so far!
