### ISSUE TITLE
[Bug] MetricFlow queries fail for `derived` metrics that use the same `ratio` metric multiple times 

### ISSUE THREAD

**Issue by waligob** [dbt-labs/metricflow#870]
### Is this a new bug in metricflow?

- [X] I believe this is a new bug in metricflow
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Given the following MetricFlow config, consisting of a `ratio` metric and a `derived` metric:
```yml

  - name: web_pageviews_per_session
    type: ratio
    type_params:
      numerator: total_web_pageviews
      denominator: total_web_sessions

  - name: web_pageviews_per_session_yoy_percent_change
    type: derived
    type_params:
      expr: (web_pageviews_per_session - web_pageviews_per_session_prev_year)*100/web_pageviews_per_session_prev_year
      metrics:
        - name: web_pageviews_per_session
        - name: web_pageviews_per_session
          offset_window: 1 year
          alias: web_pageviews_per_session_prev_year
```

The command `mf query --metrics=web_pageviews_per_session_yoy_percent_change --group-by=metric_time` fails with the message `ERROR: Database Error
  Column name total_web_pageviews is ambiguous at [9:12]`

### Expected Behavior

`mf query --metrics=web_pageviews_per_session_yoy_percent_change --group-by=metric_time` returns with a metric value.

### Steps To Reproduce

See "Current Behavior" section for steps to reproduce.

### Relevant log output

```shell
The output of `mf query --metrics=web_pageviews_per_session_yoy_percent_change --group-by=metric_time --explain` is attached here. Note that the ambiguous columns occur after the third SELECT statement.

-- Compute Metrics via Expressions
SELECT
  metric_time__day
  , (web_pageviews_per_session - web_pageviews_per_session_prev_year)*100/web_pageviews_per_session_prev_year AS web_pageviews_per_session_yoy_percent_change
FROM (
  -- Compute Metrics via Expressions
  SELECT
    metric_time__day
    , CAST(total_web_pageviews AS FLOAT64) / CAST(NULLIF(total_web_sessions, 0) AS FLOAT64) AS web_pageviews_per_session
    , CAST(total_web_pageviews AS FLOAT64) / CAST(NULLIF(total_web_sessions, 0) AS FLOAT64) AS web_pageviews_per_session_prev_year
  FROM (
    -- Constrain Output with WHERE
    -- Pass Only Elements:
    --   ['total_pageviews', 'total_sessions', 'metric_time__day']
    -- Aggregate Measures
    -- Compute Metrics via Expressions
    SELECT
      metric_time__day
      , SUM(total_pageviews) AS total_web_pageviews
      , COUNT(DISTINCT total_sessions) AS total_web_sessions
      , SUM(total_pageviews) AS total_web_pageviews
      , COUNT(DISTINCT total_sessions) AS total_web_sessions
    FROM (
      -- Read Elements From Semantic Model 'sessions'
      -- Metric Time Dimension 'date'
      -- Pass Only Elements:
      --   ['total_pageviews',
      --    'total_sessions',
      --    'session__host_platform',
      --    'metric_time__day']
      SELECT
        date AS metric_time__day
        , host_platform AS session__host_platform
        , session_key AS total_sessions
        , pageviews AS total_pageviews
      FROM `inq-warehouse`.`test`.`int_sessions` sessions_src_1
    ) subq_2
    WHERE session__host_platform = 'web'
    GROUP BY
      metric_time__day
  ) subq_6
) subq_7
-- MF_REQUEST_METADATA: {"tag_dict": {"MF_REQUEST_ID": "mf_rid__lae6t5n6"}}
```

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Python: 3.9.17
- dbt: 1.6.9
- metricflow: 0.202.0
```

### Which database are you using?

bigquery

**Comment by tlento** [comment]
Ooof. This is actually a duplicate of #757 so I'm going to merge it there, but this is not easy to resolve so it'll take some time.

I think your only work-around at the moment is to define the offset ratio metric as its own independent metric with offsets and aliases on all of the inputs to it, but I'm not 100% sure.

**Comment by tlento** [comment]
Closing in favor of the older issue, but now they're linked. Thanks for reporting!

**Comment by waligob** [comment]
Thanks, @tlento! I've found that that workaround mostly works. The following `metrics` can all be queried successfully:
```yml
  - name: web_pageviews_per_session
    type: ratio
    type_params:
      numerator: total_web_pageviews
      denominator: total_web_sessions

  - name: web_pageviews_per_session_prev_year
    type: derived
    type_params:
      expr: web_pageviews_per_session
      metrics:
        - name: web_pageviews_per_session
          offset_window: 1 year

  - name: web_pageviews_per_session_yoy_percent_change
    type: derived
    type_params:
      expr: (web_pageviews_per_session - web_pageviews_per_session_prev_year)*100/web_pageviews_per_session_prev_year
      metrics:
        - name: web_pageviews_per_session
        - name: web_pageviews_per_session_prev_year

```

`dbt parse` is being a little finicky. I kept getting the following error until I deleted the `target/` directory, after which I was able to run `dbt parse` successfully:
```
$ dbt parse
18:07:08  Running with dbt=1.6.0
18:07:09  Registered adapter: bigquery=1.6.9
18:07:10  Encountered an error:
Compilation Error
  dbt found two metrics with the name "web_pageviews_per_session_prev_year".
  
  Since these resources have the same name, dbt will be unable to find the correct resource
  when looking for web_pageviews_per_session_prev_year.
  
  To fix this, change the name of one of these resources:
  - metric.inquirer_dbt.web_pageviews_per_session_prev_year (models/marts/core/intermediate/int_sessions.yml)
  - metric.inquirer_dbt.web_pageviews_per_session_prev_year (models/marts/core/intermediate/int_sessions.yml)
```
