### ISSUE TITLE
[Feature] Abstract dimension from its underlying join path to prevent ambiguity

### ISSUE THREAD

**Issue by gowthamgutha** [dbt-labs/metricflow#963]
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing metricflow functionality, rather than a Big Idea better suited to a discussion

## Description

In MetricFlow command line, we have the `--metrics` option which allows us to give multiple metrics and we also have the `--group-by` which allows us to give multiple dimensions.
While we can aggregate a _single_ metric against multiple dimensions or _multiple_ metrics against the single dimension (provided that all those metrics have the same join path), we cannot query for multiple metrics over different join paths even though these different join paths at the end lead to the same dimension.

I will be referring to the AdventureWorks2019 schema below. You may check this ER diagram for reference (https://akela.mendelu.cz/~jprich/vyuka/db2/AdventureWorks2008_db_diagram.pdf)

For example, 
If I want to view `SumLineTotal` which is `Sum(LineTotal)` from `SalesOrderDetail` table and `SalesQuota` from `SalesPersonQuotaHistory` table grouped by `Country name`.

If you notice from the above ER diagram, that both of them map to the `CountryRegionCode` table that contains the `Country` name column but the join paths are different.

Now, if I want to see them side-by-side grouped by country, there is an ambiguity on what I need to pass on to the `--group-by` clause in the Metricflow cli. This is due to the fact that they have different join paths and the MetricFlow cannot distinguish which join path to apply for which measure.

## The issue context
A dimension is identified by the join path. The join path determines how we need to traverse to a particular dimension. Technically, a dimension can be simple like a `country` but the join paths for the country dimension can be different for different metrics owing to the semantic model where the metrics' measures are defined. Since, the dimension is technically same, we expect to query multiple metrics and view them side by side grouped by that dimension.

## Proposed solution
Currently, the join_path is considered as a dimension itself. There isn't a clear separation.
IMO, dimension is a logical abstraction while join path is an internal detail. So, we need to abstract _dimension_ from its underlying join path.

So, we should treat the `dimension` abstraction as a first-class citizen while querying metrics. The user should be giving the *dimension* name instead of the full join path. Now, the `dimension` internally refers to a join path which can be explicitly declared in the semantic model yaml. 

When multiple measures are queried for the same dimension, MetricFlow ought to figure out:
1. If the dimension exists for all the queried measures.
2. Figure out the join paths for each dimension (as defined in the semantic model yaml)
3. Traverse each join path to see if they point to the same column from the same table/model (validation step).
4. Once we figure out that all the measures point to the same dimension, we can generate SQL sub queries for each metric grouped by that join path and union both of them to give the final result.

An example command line for the user could be:

`mf query --metrics sumlinetotal,sumsalesquota--group-by-dimension country`

and the corresponding yaml could be (notice the proposed new field `join_path` in dimensions).

```yaml
version: 2
semantic_models:
  - name: salesorderdetail
    defaults:
      agg_time_dimension: modified_date
    description: |
      Items contained in each order. The grain of the table is one row per order item.
    model: ref('m_salesorderdetail')
    entities:
      - name: sales_order_detail_id
        type: primary
        expr: SalesOrderDetailID
      - name: sales_order_id
        type: foreign
        expr: SalesOrderID
    dimensions:
      - name: country
        join_path: sales_order_id__territory_id__country_region_code__name
        type: categorical
      - name: modified_date
        expr: modified_date
        type: time
        type_params:
          time_granularity: month
    measures:
      - name: sumlinetotal
        description: The revenue generated for each line order item.
        agg: sum
        expr: linetotal

  - name: sales_person_quota_history
    description: |
      sales person quota history
    model: ref('m_salespersonquotahistory')
    defaults:
      agg_time_dimension: quota_date
    entities:
      - name: sales_person_id
        type: foreign
        expr: BUSINESSENTITYID
      - name: rowguid
        type: primary
        expr: (BusinessEntityID, QuotaDate)
    dimensions:
      - name: country
        type: time
        join_path: sales_person_id__territory_id__country_region_code__name
      - name: quota_date
        type: time
        expr: QuotaDate
        type_params:
          time_granularity: month
    measures:
      - name: sum_sales_quota
        description: sales quota
        agg: sum
        expr: SalesQuota

  - name: sales_person
    description: |
      sales person
    model: ref('m_salesperson')
    defaults:
      agg_time_dimension: modified_date
    entities:
      - name: sales_person_id
        type: primary
        expr: BUSINESSENTITYID
      - name: territory_id
        type: foreign
        expr: TerritoryID
    dimensions:
      - name: modified_date
        expr: ModifiedDate
        type: time
        type_params:
          time_granularity: month


  - name: salesorderheader
    defaults:
      agg_time_dimension: order_date
    description: |
      sales order header
    model: ref('m_salesorderheader')
    entities:
      - name: sales_order_id
        type: primary
        expr: SalesOrderID
      - name: territory_id
        type: foreign
        expr: TerritoryID    
    dimensions:
      - name: order_date
        expr: OrderDate
        type: time
        type_params:
          time_granularity: month

  - name: sales_territory
    description: |
      sales territory
    model: ref('m_salesterritory')
    entities:
      - name: territory_id
        type: primary
        expr: TerritoryID
      - name: country_region_code
        type: foreign
        expr: CountryRegionCode

  - name: country_region_code
    description: |
      country region code
    model: ref('m_countryregioncode')
    entities:
      - name: country_region_code
        type: foreign
        expr: CountryRegionCode
    dimensions:
      - name: name
        type: categorical
        expr: Name


metrics:
  # Simple metrics
  - name: sumlinetotal
    description: Sum of the product line total.
    type: simple
    label: SumLineTotal
    type_params:
      measure: sumlinetotal

```

### Describe alternatives you've considered

We need to re-model in a way that the join paths for these different measures would be same. But this means to de-normalize and create intermediary models.

### Who will this benefit?

For those who want to query multiple measures grouped by the same dimension but each measure has its own join path for the dimension.
