### ISSUE TITLE
[SL-1520] [Bug] Duplicate input measure matched in plan rendering

### ISSUE THREAD

**Issue by WilliamDee** [dbt-labs/metricflow#969]
Currently, when running through the branch combiner, in an instance where you have 2 derived metrics that contains the same input measure, it would get combined and it doesn't get deduped. Example,

```
metric:
  name: "derived1"
  description: Test child derived metric 1
  type: derived
  type_params:
    expr: "booking_value + bookings"
    metrics:
      - name: booking_value
      - name: bookings
---
metric:
  name: "derived2"
  description: Test child derived metric 2
  type: derived
  type_params:
    expr: "bookings + instant_bookings"
    metrics:
      - name: instant_bookings
      - name: bookings
---
metric:
  name: "derived_parent"
  description: Test parent derived metric
  type: derived
  type_params:
    expr: "derived1 + derived2"
    metrics:
      - name: derived1
      - name: derived2
```

This leads to hitting an error during the dataflow rendering where we matched 2 duplicate input measures when expecting only 1 ([here](https://github.com/dbt-labs/metricflow/blob/main/metricflow/plan_conversion/instance_converters.py#L608)). Additionally, the parser in dbt-core utilizes it's own rewritten set of transformation rules and it currently isn't doing any deduping, this is a bug and should be fixed within dbt-core, tho it isn't affecting this issue.

<sub>From [SyncLinear.com](https://synclinear.com) | [SL-1520](https://linear.app/dbt-labs/issue/SL-1520/[bug]-duplicate-input-measure-matched-in-plan-rendering)</sub>
